"use client";

/**
 * AvatarImg — renders any stored avatar_url:
 *
 *   boring://{style}/{encodedSeed}  →  inline SVG via boring-avatars npm
 *                                      package (zero CDN dependency)
 *   https://...                     →  plain <img> tag
 *   https://source.boringavatars.com/... → local boring-avatars rendering
 *   null / undefined                →  deterministic boring-avatar from name
 *                                      (every user gets a unique avatar)
 *
 * Always use this component instead of raw <img> so the boring:// protocol
 * is handled everywhere automatically.
 */

import Avatar from "boring-avatars";

interface AvatarImgProps {
  /** The avatar_url from the database. May be null/undefined. */
  url: string | null | undefined;
  /** Name used as the seed for the generated fallback avatar (and as fallback
   *  seed when the URL does not embed one). */
  name?: string;
  size?: number;
  className?: string;
}

export function AvatarImg({
  url,
  name = "designer",
  size = 40,
  className,
}: AvatarImgProps) {
  // No URL — generate a deterministic unique avatar from the user's name so
  // every user is visually distinct even before they choose an avatar.
  if (!url) {
    return (
      <span
        style={{
          width: size,
          height: size,
          display: "inline-flex",
          borderRadius: "50%",
          overflow: "hidden",
          flexShrink: 0,
        }}
        className={className}
      >
        <Avatar size={size} name={name} variant="beam" />
      </span>
    );
  }

  if (url.startsWith("boring://")) {
    const rest = url.slice("boring://".length);
    const slashIdx = rest.indexOf("/");
    const style = slashIdx >= 0 ? rest.slice(0, slashIdx) : rest;
    const seed =
      slashIdx >= 0 ? decodeURIComponent(rest.slice(slashIdx + 1)) : name;

    return (
      <span
        style={{
          width: size,
          height: size,
          display: "inline-flex",
          borderRadius: "50%",
          overflow: "hidden",
          flexShrink: 0,
        }}
      >
        <Avatar size={size} name={seed} variant={style as "marble"} />
      </span>
    );
  }

  // Keep avatars generated by older k6 seeders working even when the
  // source.boringavatars.com endpoint is unavailable. The email/seed is kept
  // in the path, so every load-test user still gets a stable distinct avatar.
  if (url.startsWith("https://source.boringavatars.com/")) {
    try {
      const parsed = new URL(url);
      const [, style, , encodedSeed] = parsed.pathname.split("/");
      const seed = encodedSeed ? decodeURIComponent(encodedSeed) : name;
      if (style && seed) {
        return (
          <span
            style={{
              width: size,
              height: size,
              display: "inline-flex",
              borderRadius: "50%",
              overflow: "hidden",
              flexShrink: 0,
            }}
          >
            <Avatar size={size} name={seed} variant={style as "marble"} />
          </span>
        );
      }
    } catch {
      // Fall through to the normal image renderer for malformed legacy URLs.
    }
  }

  // Standard URL (DiceBear, Robohash, Avataaars, uploaded file)
  // eslint-disable-next-line @next/next/no-img-element
  return (
    <img
      src={url}
      alt="Avatar"
      width={size}
      height={size}
      className={className}
    />
  );
}
